services:
  # Development Environment Service
  web-dev:
    build:
      context: .
      target: development
    profiles: ["dev"]
    ports:
      - "80:5000"
    volumes:
      # Mount the local src directory to enable live reloading
      - ./src:/app/src
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg://edwin:password@db:5432/db
    depends_on:
      - db

  web-prod:
    build:
      context: .
      target: production
    profiles: ["prod"]
    ports:
      - "80:8000"
    restart: always
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=production
      - DATABASE_URL=postgresql+psycopg://edwin:password@db:5432/db
    depends_on:
      - db

  db:
    image: postgres:14.22
    container_name: db
    profiles: ["dev", "prod"]
    restart: always
    environment:
      - POSTGRES_USER=edwin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
