services:
  flask-app:
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      FLASK_DEBUG: "1"
    volumes:
      - .:/app:cached
    working_dir: /app

  db:
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_PASSWORD_FILE: ""
    secrets: []
    ports:
      - "5432:5432"

volumes:
  db-data-dev:
    name: db-dev