services:
  flask-app:
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      FLASK_DEBUG: "1"
    volumes:
      - .:/app:cached
    working_dir: /app

  db:
    env_file:
      - .env
    # Disable secrets in dev.
    secrets: [ ]
    environment:
      POSTGRES_PASSWORD_FILE: ""
    ports:
      - "5432:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"   # Web UI
      - "9092:9092"   # Internal communication
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  db-data-dev:
    name: db-dev
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: